translations = {
    "clearsky_day": "Ясное небо (день)",
    "clearsky_night": "Ясное небо (ночь)",
    "clearsky_polartwilight": "Ясное небо (полярные сумерки)",
    "cloudy": "Облачно",
    "fair_day": "Ясно (день)",
    "fair_night": "Ясно (ночь)",
    "fair_polartwilight": "Ясно (полярные сумерки)",
    "fog": "Туман",
    "heavyrain": "Сильный дождь",
    "heavyrainandthunder": "Сильный дождь и гроза",
    "heavyrainshowers_day": "Сильные дождевые ливни (день)",
    "heavyrainshowers_night": "Сильные дождевые ливни (ночь)",
    "heavyrainshowers_polartwilight": "Сильные дождевые ливни (полярные сумерки)",
    "heavyrainshowersandthunder_day": "Сильные дождевые ливни и гроза (день)",
    "heavyrainshowersandthunder_night": "Сильные дождевые ливни и гроза (ночь)",
    "heavyrainshowersandthunder_polartwilight": "Сильные дождевые ливни и гроза (полярные сумерки)",
    "heavysleet": "Сильный мокрый снег",
    "heavysleetandthunder": "Сильный мокрый снег и гроза",
    "heavysleetshowers_day": "Сильные ливни мокрого снега (день)",
    "heavysleetshowers_night": "Сильные ливни мокрого снега (ночь)",
    "heavysleetshowers_polartwilight": "Сильные ливни мокрого снега (полярные сумерки)",
    "heavysleetshowersandthunder_day": "Сильные ливни мокрого снега и гроза (день)",
    "heavysleetshowersandthunder_night": "Сильные ливни мокрого снега и гроза (ночь)",
    "heavysleetshowersandthunder_polartwilight": "Сильные ливни мокрого снега и гроза (полярные сумерки)",
    "heavysnow": "Сильный снегопад",
    "heavysnowandthunder": "Сильный снегопад и гроза",
    "heavysnowshowers_day": "Сильные ливни снега (день)",
    "heavysnowshowers_night": "Сильные ливни снега (ночь)",
    "heavysnowshowers_polartwilight": "Сильные ливни снега (полярные сумерки)",
    "heavysnowshowersandthunder_day": "Сильные ливни снега и гроза (день)",
    "heavysnowshowersandthunder_night": "Сильные ливни снега и гроза (ночь)",
    "heavysnowshowersandthunder_polartwilight": "Сильные ливни снега и гроза (полярные сумерки)",
    "lightrain": "Легкий дождь",
    "lightrainandthunder": "Легкий дождь и гроза",
    "lightrainshowers_day": "Легкие дождевые ливни (день)",
    "lightrainshowers_night": "Легкие дождевые ливни (ночь)",
    "lightrainshowers_polartwilight": "Легкие дождевые ливни (полярные сумерки)",
    "lightrainshowersandthunder_day": "Легкие дождевые ливни и гроза (день)",
    "lightrainshowersandthunder_night": "Легкие дождевые ливни и гроза (ночь)",
    "lightrainshowersandthunder_polartwilight": "Легкие дождевые ливни и гроза (полярные сумерки)",
    "lightsleet": "Легкий мокрый снег",
    "lightsleetandthunder": "Легкий мокрый снег и гроза",
    "lightsleetshowers_day": "Легкие ливни мокрого снега (день)",
    "lightsleetshowers_night": "Легкие ливни мокрого снега (ночь)",
    "lightsleetshowers_polartwilight": "Легкие ливни мокрого снега (полярные сумерки)",
    "lightsnow": "Легкий снегопад",
    "lightsnowandthunder": "Легкий снегопад и гроза",
    "lightsnowshowers_day": "Легкие ливни снега (день)",
    "lightsnowshowers_night": "Легкие ливни снега (ночь)",
    "lightsnowshowers_polartwilight": "Легкие ливни снега (полярные сумерки)",
    "lightssleetshowersandthunder_day": "Легкие ливни мокрого снега и гроза (день)",
    "lightssleetshowersandthunder_night": "Легкие ливни мокрого снега и гроза (ночь)",
    "lightssleetshowersandthunder_polartwilight": "Легкие ливни мокрого снега и гроза (полярные сумерки)",
    "lightssnowshowersandthunder_day": "Легкие ливни снега и гроз",
    "lightssnowshowersandthunder_night": "Легкие ливни снега и гроза (ночь)",
    "lightssnowshowersandthunder_polartwilight": "Легкие ливни снега и гроза (полярные сумерки)",
    "partlycloudy_day": "Переменная облачность (день)",
    "partlycloudy_night": "Переменная облачность (ночь)",
    "partlycloudy_polartwilight": "Переменная облачность (полярные сумерки)",
    "rain": "Дождь",
    "rainandthunder": "Дождь и гроза",
    "rainshowers_day": "Дождевые ливни (день)",
    "rainshowers_night": "Дождевые ливни (ночь)",
    "rainshowers_polartwilight": "Дождевые ливни (полярные сумерки)",
    "rainshowersandthunder_day": "Дождевые ливни и гроза (день)",
    "rainshowersandthunder_night": "Дождевые ливни и гроза (ночь)",
    "rainshowersandthunder_polartwilight": "Дождевые ливни и гроза (полярные сумерки)",
    "sleet": "Мокрый снег",
    "sleetandthunder": "Мокрый снег и гроза",
    "sleetshowers_day": "Ливни мокрого снега (день)",
    "sleetshowers_night": "Ливни мокрого снега (ночь)",
    "sleetshowers_polartwilight": "Ливни мокрого снега (полярные сумерки)",
    "sleetshowersandthunder_day": "Ливни мокрого снега и гроза (день)",
    "sleetshowersandthunder_night": "Ливни мокрого снега и гроза (ночь)",
    "sleetshowersandthunder_polartwilight": "Ливни мокрого снега и гроза (полярные сумерки)",
    "snow": "Снегопад",
    "snowandthunder": "Снегопад и гроза",
    "snowshowers_day": "Ливни снега (день)",
    "snowshowers_night": "Ливни снега (ночь)",
    "snowshowers_polartwilight": "Ливни снега (полярные сумерки)",
    "snowshowersandthunder_day": "Ливни снега и гроза (день)",
    "snowshowersandthunder_night": "Ливни снега и гроза (ночь)",
    "snowshowersandthunder_polartwilight": "Ливни снега и гроза (полярные сумерки)"
}